const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');const Module=require('node:module');const m=new Module(__filename);m._compile(ts.transpileModule(fs.readFileSync('src/utils/recipeSelection.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,__filename);const {selectRecipes,matchesRecipeCategory,collectRecipePages,DEFAULT_RECIPE_SELECTION:d}=m.exports;
const breakfast={_id:'1',title:'Crêpes',tags:['Petit-déjeuner'],calories:250,protein:22,preparationTimeMinutes:10,ingredients:[{name:'Oeufs'},{name:'Farine'}]};const lunch={_id:'2',title:'Poulet',tags:['Déjeuner'],calories:420,preparationTimeMinutes:25,ingredients:[{name:'Poulet'},{name:'Riz'}]};
test('breakfast and lunch categories do not overlap',()=>{assert.equal(matchesRecipeCategory(breakfast,'dejeuner'),false);assert.equal(matchesRecipeCategory(lunch,'petit_dej'),false);assert.equal(matchesRecipeCategory(breakfast,'petit_dej'),true)});
test('missing nutrition and preparation data do not match thresholds',()=>{for(const c of ['faible_kcal','rapide','proteine'])assert.equal(matchesRecipeCategory({_id:'3',title:'Unknown'},c),false)});
test('search ignores accents and includes ingredient names',()=>{assert.equal(selectRecipes([breakfast,lunch],d,'crepes',[],false).length,1);assert.equal(selectRecipes([breakfast,lunch],d,'riz',[],false)[0]._id,'2')});
test('combined favorites and preparation filters',()=>{assert.equal(selectRecipes([breakfast,lunch],{...d,prep:'15'},'', ['2'],true).length,0)});
test('ingredient matching excludes zero matches and requires all when selected',()=>{assert.equal(selectRecipes([breakfast,lunch],{...d,ingredients:['oeuf']},'',[],false).length,1);assert.equal(selectRecipes([breakfast],{...d,ingredients:['oeuf'],match:'all'},'',[],false).length,0);assert.equal(selectRecipes([breakfast],{...d,ingredients:['oeuf','farine'],match:'all'},'',[],false).length,1)});
test('loads every page and deduplicates before filtering',async()=>{const calls=[];const recipes=await collectRecipePages(async page=>{calls.push(page);return {recipes:page===1?[breakfast]:[breakfast,lunch],totalPages:2}});assert.deepEqual(calls,[1,2]);assert.equal(recipes.length,2)});
test('canceled catalog requests stop',async()=>{const c=new AbortController();c.abort();await assert.rejects(collectRecipePages(async()=>{throw Error('should not fetch')},c.signal),/Cancelled/)});
